name: Lint
on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  MODULE_NAME: clairvoyance

jobs:
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Setup poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run lint
        if: always()
        run: |
          source .venv/bin/activate
          isort -m 9 --line-length 160 $MODULE_NAME tests --check-only
          pylint --load-plugins pylint_quotes $MODULE_NAME tests
          docformatter --wrap-summaries 160 --wrap-descriptions 160 -cr $MODULE_NAME tests
          yapf -rd $MODULE_NAME tests
          mypy -V
          mypy $MODULE_NAME tests
